repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/Scripts/pip3 freeze > requirements.txt ; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]

  - repo: https://github.com/pytest-dev/pytest
    rev: HEAD  # Usa a versão mais atual do repositório pytest
    hooks:
      - id: pytest